/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pseudorandnumgen;

/**
 *
 * @author arieltodoki
 */
public class PrngGui extends javax.swing.JFrame {

    /**
     * Creates new form PrngGui
     */
    public PrngGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        middleSqLabel = new javax.swing.JLabel();
        linearLabel = new javax.swing.JLabel();
        middleScrollPane = new javax.swing.JScrollPane();
        middleTextArea = new javax.swing.JTextArea();
        linearScrollPane = new javax.swing.JScrollPane();
        linearTextArea = new javax.swing.JTextArea();
        mSeedTextField = new javax.swing.JTextField();
        mAmtTextField = new javax.swing.JTextField();
        cSeedTextField = new javax.swing.JTextField();
        cMultTextField = new javax.swing.JTextField();
        cIncTextField = new javax.swing.JTextField();
        cModTextField = new javax.swing.JTextField();
        cAmtTextField = new javax.swing.JTextField();
        mSeedLabel = new javax.swing.JLabel();
        mAmtLabel = new javax.swing.JLabel();
        cSeedLabel = new javax.swing.JLabel();
        cMultLabel = new javax.swing.JLabel();
        cIncLabel = new javax.swing.JLabel();
        cModLabel = new javax.swing.JLabel();
        cAmtLabel = new javax.swing.JLabel();
        mButton = new javax.swing.JButton();
        cButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        middleSqLabel.setText("Middle Square");
        getContentPane().add(middleSqLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        linearLabel.setText("Linear Congruential Generator");
        getContentPane().add(linearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        middleScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        middleTextArea.setColumns(20);
        middleTextArea.setRows(5);
        middleScrollPane.setViewportView(middleTextArea);

        getContentPane().add(middleScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 136, 168));

        linearScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        linearScrollPane.setToolTipText("");

        linearTextArea.setColumns(20);
        linearTextArea.setRows(5);
        linearScrollPane.setViewportView(linearTextArea);

        getContentPane().add(linearScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 180, 170));
        getContentPane().add(mSeedTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 90, -1));
        getContentPane().add(mAmtTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 80, -1));
        getContentPane().add(cSeedTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 80, -1));
        getContentPane().add(cMultTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 80, -1));
        getContentPane().add(cIncTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 80, -1));
        getContentPane().add(cModTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 80, -1));
        getContentPane().add(cAmtTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 90, -1));

        mSeedLabel.setText("Seed (2,4,6)");
        getContentPane().add(mSeedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        mAmtLabel.setText("#'s Generated");
        getContentPane().add(mAmtLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        cSeedLabel.setText("Seed");
        getContentPane().add(cSeedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        cMultLabel.setText("Multiplier");
        getContentPane().add(cMultLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        cIncLabel.setText("Increment");
        getContentPane().add(cIncLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        cModLabel.setText("Mod");
        getContentPane().add(cModLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        cAmtLabel.setText("#'s Generated");
        getContentPane().add(cAmtLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        mButton.setText("Generate");
        mButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButtonActionPerformed(evt);
            }
        });
        getContentPane().add(mButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        cButton.setText("Generate");
        cButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButtonActionPerformed
        // TODO add your handling code here:
        middleTextArea.setLineWrap(true);
        middleTextArea.setWrapStyleWord(true);
        
        middleTextArea.setText("");
        String input = mSeedTextField.getText();
        long seed = Integer.parseInt(input);
        middleTextArea.append(seed+", ");
        int length = input.trim().length();
        

        int amt = Integer.parseInt(mAmtTextField.getText());


        int[] divide = {0,10,100,1000};
        for(int i = 0; i < amt; i++){
            long sqr = seed*seed;
            seed = (sqr/divide[length/2])%(divide[length/2]*divide[length/2]);

            middleTextArea.append(seed+", ");
        }
    
        
    }//GEN-LAST:event_mButtonActionPerformed

    private void cButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
        // TODO add your handling code here:
        linearTextArea.setLineWrap(true);
        linearTextArea.setWrapStyleWord(true);
        
        linearTextArea.setText("");
        long seed = Integer.parseInt(cSeedTextField.getText());
        linearTextArea.append(seed+", ");
        long a = Integer.parseInt(cMultTextField.getText());
        long c = Integer.parseInt(cIncTextField.getText());
        long m = Integer.parseInt(cModTextField.getText());
        int amt = Integer.parseInt(cAmtTextField.getText());
        
        for(int i = 0; i<amt; i++){
            seed = (a*seed+c)%m;
            linearTextArea.append(seed+", ");
        }
    }//GEN-LAST:event_cButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrngGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrngGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrngGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrngGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrngGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cAmtLabel;
    private javax.swing.JTextField cAmtTextField;
    private javax.swing.JButton cButton;
    private javax.swing.JLabel cIncLabel;
    private javax.swing.JTextField cIncTextField;
    private javax.swing.JLabel cModLabel;
    private javax.swing.JTextField cModTextField;
    private javax.swing.JLabel cMultLabel;
    private javax.swing.JTextField cMultTextField;
    private javax.swing.JLabel cSeedLabel;
    private javax.swing.JTextField cSeedTextField;
    private javax.swing.JLabel linearLabel;
    private javax.swing.JScrollPane linearScrollPane;
    private javax.swing.JTextArea linearTextArea;
    private javax.swing.JLabel mAmtLabel;
    private javax.swing.JTextField mAmtTextField;
    private javax.swing.JButton mButton;
    private javax.swing.JLabel mSeedLabel;
    private javax.swing.JTextField mSeedTextField;
    private javax.swing.JScrollPane middleScrollPane;
    private javax.swing.JLabel middleSqLabel;
    private javax.swing.JTextArea middleTextArea;
    // End of variables declaration//GEN-END:variables




}
